name: trivy

on:
  push:
    tags:
      - '*'
  schedule:
    - cron: '44 19 * * 4'
  workflow_call:

permissions:
  contents: read

env:
  DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
  DOCKERHUB_REPOSITORY: ${{ vars.DOCKERHUB_REPOSITORY }}
  TRIVY_DB_REPOSITORY: 'public.ecr.aws/aquasecurity/trivy-db'
  TRIVY_JAVA_DB_REPOSITORY: 'public.ecr.aws/aquasecurity/trivy-java-db'

jobs:
  scan:
    permissions:
      contents: read
      security-events: write

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v5

      - name: Build an image from Dockerfile
        run: |
          docker build -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPOSITORY }}:dev .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: '${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPOSITORY }}:dev'
          format: 'table'
          exit-code: 0
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Store Trivy vulnerability scanner output
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: '${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPOSITORY }}:dev'
          format: 'sarif'
          output: 'trivy-results.sarif'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'trivy-results.sarif'
